create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'student' check (role in ('student', 'teacher')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  event_code text primary key,
  title text not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  event_code text not null references public.events(event_code) on delete cascade,
  scanned_at timestamptz not null default now(),
  unique (student_id, event_code)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', null),
    coalesce(new.raw_user_meta_data ->> 'role', 'student')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = excluded.full_name,
        role = excluded.role,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.attendance enable row level security;

create policy if not exists "Profiles are viewable by owner"
on public.profiles
for select
using (auth.uid() = id);

create policy if not exists "Users can update their own profile"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy if not exists "Teachers can create their own events"
on public.events
for insert
with check (auth.uid() = created_by and exists (
  select 1 from public.profiles p
  where p.id = auth.uid() and p.role = 'teacher'
));

create policy if not exists "Teachers can view their own events"
on public.events
for select
using (auth.uid() = created_by);

create policy if not exists "Students can insert their own attendance"
on public.attendance
for insert
with check (auth.uid() = student_id);

create policy if not exists "Users can view their own attendance"
on public.attendance
for select
using (auth.uid() = student_id);

create policy if not exists "Teachers can view attendance for their events"
on public.attendance
for select
using (exists (
  select 1
  from public.events e
  where e.event_code = public.attendance.event_code
    and e.created_by = auth.uid()
));

create policy if not exists "Teachers can view profiles of their attendees"
on public.profiles
for select
using (
  exists (
    select 1
    from public.attendance a
    join public.events e on e.event_code = a.event_code
    where a.student_id = public.profiles.id
      and e.created_by = auth.uid()
  )
);

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute procedure public.update_updated_at_column();
